// Real, read-only Quiver material. Generated by scripts/build-data.mjs. Never hand-edit the JSON.
import raw from './generated/quiver.json';

export interface Supplier { name: string; partNumber: string | null; url: string | null; note: string | null }
export interface Part { id: string; name: string; qty: number; sourcing: string | null; material: string | null; spec: string | null; unitCostUsd: number | null; designRef: string | null; notes: string | null; suppliers: Supplier[] }
export interface BomGroup { category: string; name: string; items: Part[] }
export interface Milestone { n: number; title: string; text: string }
export interface Task { id: string; number: number; url: string; title: string; state: string; claimable: boolean; fundingLabel: string | null; priceText: string | null; priceUsd: number | null; fundingText: string | null; owner: string | null; deadline: string | null; doneWhen: string | null; status: string | null; whoShouldClaim: string | null; milestones: Milestone[]; body: string; topics: string[]; parts: string[]; comments: number; updatedAt: string }
export interface Issue { number: number; url: string; title: string; state: string; labels: string[]; excerpt: string; topics: string[]; parts: string[]; comments: number; createdAt: string; updatedAt: string }
export interface FundingLine { label: string; name: string; statedBudgetUsd: number | null; statedBudgetSource: string | null; pricedUsd: number; unpriced: number; tasks: string[] }
export interface Flight { id: string; date: string | null; location: string | null; aircraft: string | null; weather: string | null; wind: string | null; aim: string | null; path: string }
export interface Guide { group: string; path: string; title: string; lines: number; outline: { depth: number; text: string }[] }

export const q = raw as unknown as {
  generatedAt: string;
  sources: { repo: string; bomConfig: string; bomDate: string; bomTitle: string };
  bom: BomGroup[]; tasks: Task[]; issues: Issue[]; fundingLines: FundingLine[]; flights: Flight[]; guides: Guide[];
  devGuideMd: string; attachmentSpec: { status: string | null; date: string | null; purpose: string | null; url: string };
};

export const parts: Part[] = q.bom.flatMap((g) => g.items);
export const partById = new Map(parts.map((p) => [p.id, p]));
export const groupOf = (id: string) => q.bom.find((g) => g.items.some((i) => i.id === id));
export const taskById = new Map(q.tasks.map((t) => [t.id, t]));
export const openIssues = q.issues.filter((i) => i.state === 'OPEN');
export const bomCostUsd = parts.reduce((a, p) => a + (p.unitCostUsd ?? 0) * p.qty, 0);
export const repoFile = (path: string) => `${q.sources.repo}/blob/main/${path}`;
export const usd = (n: number) => '$' + n.toLocaleString('en-US', { maximumFractionDigits: 0 });
export const owned = (t: Task) => !!t.owner && !/^OPEN/i.test(t.owner);
export const ownerName = (t: Task) => (owned(t) ? t.owner!.replace(/\s*\(.*$/, '') : null);
