import { expect, it } from 'vitest';
import { seedState } from '../data/seed';
import { installDeliverySamples } from '../data/sampleDelivery';
import { projectBriefing, nextWorkStep } from './projectBriefing';
function setup(){const s=seedState();installDeliverySamples(s);const bundles=s.threads.map(thread=>({thread,positions:s.positions.filter(p=>p.threadId===thread.id),comments:[],votes:[],intents:[]}));const project=s.projects.find(p=>p.id==='spearhead')!;const brief=(version='sh-pt2')=>projectBriefing(project,version,bundles,s.decisions,s.grants,s.specifications??[]);return {s,brief};}
it('does not present a replaced decision as current or research as adopted design',()=>{const {brief}=setup();const avionics=brief().systems.find(s=>s.system==='avionics')!;expect(avionics.design).toHaveLength(1);expect(avionics.design[0].supersedesIds).toHaveLength(1);const propulsion=brief().systems.find(s=>s.system==='propulsion')!;expect(propulsion.work.some(g=>g.workPurpose==='research')).toBe(true);expect(propulsion.design).toHaveLength(0);});
it('does not leak future work into an earlier baseline',()=>{const {brief}=setup();expect(brief('sh-pt1').work).toHaveLength(0);expect(brief('sh-pt1').effective).toHaveLength(0);});
it('connects cross-system work via decision links without duplicating a work item',()=>{const {s,brief}=setup();const g=s.grants.find(g=>g.id==='sample-delivery-keyed-harness')??s.grants.find(g=>g.title==='Build the keyed avionics harness')!;const airframe=brief().systems.find(s=>s.system==='airframe')!.design[0];g.decisionIds!.push(airframe.id);expect(brief().systems.find(s=>s.system==='airframe')!.work.filter(w=>w.id===g.id)).toHaveLength(1);expect(brief().systems.find(s=>s.system==='avionics')!.work.filter(w=>w.id===g.id)).toHaveLength(1);});
it('flags stale sources and unincorporated decisions separately',()=>{const {s,brief}=setup();const section=s.specifications!.find(s=>s.system==='avionics')!;section.decisionIds=[brief().systems.find(s=>s.system==='avionics')!.design[0].supersedesIds![0]];expect(brief().stale.map(s=>s.system)).toContain('avionics');expect(brief().missing.some(d=>d.chosen.includes('Physically key'))).toBe(true);});
it('does not confuse accepted delivery with recorded payment',()=>{const {s}=setup();const g=s.grants.find(g=>g.tracking?.stage==='completed'&&g.tracking.funding==='funded')!;expect(nextWorkStep(g,s.members)).toContain('payment not recorded');g.tracking!.funding='paid';expect(nextWorkStep(g,s.members)).toContain('payment recorded');});
