<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import Markdown from './Markdown.vue';
import FollowUp from './FollowUp.vue';
import { backend, act, handleOf, myRoleOn, state } from '../data/store';
import type { Decision, Grant, Project, SpecificationSection, Version } from '../lib/types';
import type { ThreadBundle } from '../data/backend';
import { currentDecisions, designDecisions, effectiveSections, trackingOf, workStages } from '../lib/projectRecords';
import { useUnsaved } from '../composables/useUnsaved';
const props = defineProps<{ project: Project; version: Version; decisions: Decision[]; grants: Grant[]; bundles: ThreadBundle[] }>();
const emit = defineEmits<{ navigate: [view: string, query?: Record<string, string | undefined>] }>();
const route = useRoute(), sections = ref<SpecificationSection[]>([]), search = ref(''), editing = ref(false), body = ref(''), ids = ref<string[]>([]), note = ref(''), dirty = ref(false), busy = ref(false), baseRevision = ref(0);
const replaceIds = ref<string[]>([]), replaceNote = ref('');
useUnsaved(dirty);
watch(() => state.version, async () => { try { sections.value = await backend.listSpecifications(); } catch(e) { state.error = String(e); } }, { immediate: true });
const system = computed(() => String(route.query.system ?? ''));
const history = computed(() => route.query.mode === 'history');
const current = computed(() => currentDecisions(props.project, props.version.id, props.decisions));
const applicable = computed(() => designDecisions(props.project, props.version.id, props.decisions));
const effective = computed(() => effectiveSections(props.project, props.version.id, sections.value));
const selectedSection = computed(() => effective.value.find(s => s.system === system.value));
const selectedDecision = computed(() => applicable.value.find(d => d.id === route.query.decision));
const lead = computed(() => myRoleOn(props.project.id) === 'lead');
const editable = computed(() => lead.value && ['discussing', 'planned'].includes(props.version.state));
const decisionSystem = (d: Decision) => props.bundles.find(b => b.thread.id === d.threadId)?.thread.system ?? 'project-wide';
const visible = computed(() => (history.value ? applicable.value : current.value).filter(d => (!system.value || decisionSystem(d) === system.value) && `${d.chosen} ${d.question} ${d.outcomeSnapshot?.body ?? ''}`.toLowerCase().includes(search.value.toLowerCase())));
const missing = computed(() => current.value.filter(d => !effective.value.some(s => s.decisionIds.includes(d.id))));
const stale = (s: SpecificationSection) => s.decisionIds.some(id => !current.value.some(d => d.id === id));
const sources = (s: SpecificationSection) => s.decisionIds.map(id => props.decisions.find(d => d.id === id)).filter((d): d is Decision => !!d);
const detailBody = (d: Decision) => d.outcomeSnapshot?.body ?? d.briefSnapshot?.purpose ?? props.bundles.find(b => b.thread.id === d.threadId)?.positions.find(p => p.id === d.positionId)?.body ?? d.chosen;
function nav(query: Record<string, string | undefined> = {}) { emit('navigate', 'design', { system: system.value || undefined, mode: history.value ? 'history' : undefined, ...query }); }
function edit() { const s = selectedSection.value; body.value = s?.body ?? ''; ids.value = [...(s?.decisionIds ?? current.value.filter(d => decisionSystem(d) === system.value).map(d => d.id))].filter(id => current.value.some(d => d.id === id)); note.value = ''; baseRevision.value = s?.versionId === props.version.id ? s.revision : 0; editing.value = true; dirty.value = false; }
watch([body, ids, note], () => { if (editing.value) dirty.value = true; }, { deep: true, flush: 'sync' });
watch(() => route.fullPath, () => { editing.value = false; dirty.value = false; replaceIds.value = []; replaceNote.value = ''; });
function cancelEdit() { if (!dirty.value || confirm('Discard unsaved changes?')) {editing.value=false;dirty.value=false;} }
async function save() { busy.value = true; const ok = await act(() => backend.saveSpecification({ projectId: props.project.id, versionId: props.version.id, system: system.value, expectedRevision: baseRevision.value, body: body.value, decisionIds: ids.value, note: note.value })); busy.value = false; if (ok) { dirty.value = false; editing.value = false; } }
async function replace() { if (!selectedDecision.value) return; busy.value = true; await act(() => backend.supersedeDecisions({ decisionId: selectedDecision.value!.id, supersedesIds: replaceIds.value, note: replaceNote.value })); busy.value = false; }
</script>
<template>
  <section class="records-view design-view">
    <div class="section-heading"><div><span class="eyebrow">DESIGN / {{ version.name }}</span><h2>What we’ve agreed.</h2><p>The current specification, with the decisions and evidence behind it.</p></div><button class="btn btn-ghost" @click="emit('navigate', 'review')">Design review</button></div>
    <div class="record-summary"><div><b>{{ effective.length }}</b><span>specification sections</span></div><div><b>{{ current.length }}</b><span>current decisions</span></div><div><b>{{ missing.length }}</b><span>awaiting integration</span></div><span class="baseline-badge">{{ ['building','frozen'].includes(version.state) ? 'Locked baseline' : 'Evolving baseline' }} · {{ version.name }}</span></div>
    <div class="records-toolbar"><nav class="record-switch" aria-label="Design views"><button :class="{active: !history}" @click="nav({ mode: undefined, decision: undefined })">Current specification</button><button :class="{active: history}" @click="nav({ mode: 'history', decision: undefined })">Decision history</button></nav><label><span class="sr-only">Design subsystem</span><select aria-label="Design subsystem" :value="system" @change="nav({system: ($event.target as HTMLSelectElement).value || undefined, decision: undefined})"><option value="">All subsystems</option><option v-for="s in [...project.systems, 'project-wide']" :key="s" :value="s">{{ s }}</option></select></label><input v-model="search" type="search" aria-label="Search design" placeholder="Find an adopted decision…" /></div>
    <article v-if="selectedDecision" class="record-document decision-detail">
      <button class="text-action" @click="nav({decision: undefined})">← Back to design</button><span class="eyebrow">{{ current.some(d => d.id === selectedDecision!.id) ? 'CURRENT DECISION' : 'SUPERSEDED DECISION' }} / {{ decisionSystem(selectedDecision) }}</span><h2>{{ selectedDecision.chosen }}</h2><p class="small muted">Adopted by @{{ handleOf(selectedDecision.byMemberId) }} · {{ new Date(selectedDecision.at).toLocaleDateString() }} · {{ project.versions.find(v => v.id === selectedDecision!.versionId)?.name }}</p><Markdown :source="detailBody(selectedDecision)" /><p v-if="selectedDecision.rationale"><b>Rationale:</b> {{ selectedDecision.rationale }}</p>
      <button class="text-action" @click="emit('navigate', 'shape', {thread: selectedDecision.threadId, version: selectedDecision.versionId, tab:'draft'})">Read the source discussion →</button>
      <section v-if="selectedDecision.supersedesIds?.length" class="context-note"><b>Replaces earlier decisions</b><p>{{ selectedDecision.supersessionNote }}</p><button v-for="id in selectedDecision.supersedesIds" :key="id" class="text-action" @click="nav({decision:id})">{{ decisions.find(d => d.id === id)?.chosen }} →</button></section>
      <section v-if="applicable.some(d => d.supersedesIds?.includes(selectedDecision!.id))" class="context-note"><b>Replaced in this baseline by</b><button v-for="d in applicable.filter(d => d.supersedesIds?.includes(selectedDecision!.id))" :key="d.id" class="text-action" @click="nav({decision:d.id})">{{ d.chosen }} →</button></section>
      <h3>Linked work & evidence</h3><p v-if="!grants.some(g => g.decisionIds?.includes(selectedDecision!.id))" class="muted">No commissioned work yet.</p><article v-for="g in grants.filter(g => g.decisionIds?.includes(selectedDecision!.id))" :key="g.id" class="linked-record"><button class="text-action" @click="emit('navigate', 'work', {grant:g.id, version:g.versionId})">{{ g.title }} →</button><span class="chip">{{ workStages[trackingOf(g).stage] }}</span><Markdown v-if="trackingOf(g).evidence" :source="trackingOf(g).evidence" /><p v-if="trackingOf(g).stage === 'completed'" class="small">Accepted by @{{ handleOf([...trackingOf(g).history].reverse().find(h => h.content.stage === 'completed')?.byMemberId ?? g.byMemberId) }}</p></article>
      <button v-if="lead" class="text-action" @click="emit('navigate','work',{from:selectedDecision.threadId,version:selectedDecision.versionId})">Commission work from this outcome →</button>
      <details v-if="editable && selectedDecision.versionId === version.id && !selectedDecision.supersedesIds?.length && current.some(d=>d.id===selectedDecision!.id)" class="record-followup"><summary>This decision replaces an earlier choice</summary><p class="small muted">Link what it replaces. Earlier baselines and source documents remain unchanged.</p><label v-for="d in current.filter(d => d.id !== selectedDecision!.id)" :key="d.id" class="record-check"><input v-model="replaceIds" type="checkbox" :value="d.id" />{{ d.chosen }}</label><label class="field-row">Reason for replacement<textarea v-model="replaceNote" /></label><button class="btn" :disabled="busy || !replaceIds.length || !replaceNote.trim()" @click="replace">Record replacement</button></details>
      <FollowUp :key="selectedDecision.id" :decision-id="selectedDecision.id" :title="selectedDecision.chosen" />
      <div v-if="bundles.some(b => b.thread.sourceDecisionId === selectedDecision!.id)" class="linked-record"><h3>Follow-up discussions</h3><button v-for="b in bundles.filter(b => b.thread.sourceDecisionId === selectedDecision!.id)" :key="b.thread.id" class="text-action" @click="emit('navigate','shape',{thread:b.thread.id,version:b.thread.versionId})">{{ b.thread.title }} →</button></div>
    </article>
    <template v-else>
      <template v-if="!history">
        <p v-if="missing.length" class="context-note">{{ missing.length }} adopted decision{{ missing.length === 1 ? '' : 's' }} still need integration into the specification. Adoption records the decision; the lead reviews how it changes the current document.</p>
        <div v-if="!system" class="specification-grid"><button v-for="s in [...project.systems, 'project-wide']" :key="s" class="specification-card" @click="nav({system:s})"><span class="eyebrow">{{ s }}</span><h3>{{ effective.find(x => x.system === s) ? 'Read specification' : 'Not documented yet' }}</h3><p>{{ current.filter(d => decisionSystem(d) === s).length }} current decisions</p><span v-if="effective.find(x=>x.system===s)" class="small">{{ stale(effective.find(x=>x.system===s)!) ? 'Needs reconciliation' : 'Source-linked document' }} →</span><span v-else class="small">{{ editable ? 'Develop this section →' : 'Explore decisions →' }}</span></button></div>
        <article v-else class="record-document specification-document"><div class="section-heading"><div><span class="eyebrow">SPECIFICATION / {{ system }}</span><h2>{{ system.charAt(0).toUpperCase() + system.slice(1) }}</h2></div><button v-if="editable && !editing" class="btn" @click="edit">{{ selectedSection ? 'Revise specification' : 'Write specification' }}</button></div>
          <form v-if="editing" class="stack" @submit.prevent="save"><label class="field-row">Specification document<textarea v-model="body" aria-label="Specification document" class="document-editor" required placeholder="The current requirements and design for this subsystem. Synthesize the linked decisions into one readable document." /></label><fieldset><legend>Source decisions</legend><label v-for="d in current" :key="d.id" class="record-check"><input v-model="ids" type="checkbox" :value="d.id" />{{ d.chosen }}</label></fieldset><label class="field-row">Revision note<input v-model="note" aria-label="Specification revision note" required placeholder="What changed and why?" /></label><p class="small muted">Saving records your reviewed specification. A document can combine decisions from several discussions.</p><div class="row"><button class="btn" :disabled="busy || !ids.length">Save reviewed specification</button><button type="button" class="btn btn-ghost" @click="cancelEdit">Cancel</button></div></form>
          <template v-else-if="selectedSection"><p class="small muted">Revision {{ selectedSection.revision }} · @{{ handleOf(selectedSection.updatedBy) }} · {{ selectedSection.versionId === version.id ? version.name : `Inherited from ${project.versions.find(v=>v.id===selectedSection!.versionId)?.name}` }}</p><p v-if="stale(selectedSection)" class="context-note">A source decision has been replaced. This specification needs reconciliation; its text has not been silently changed.</p><Markdown :source="selectedSection.body" /><h3>Decisions behind this section</h3><button v-for="d in sources(selectedSection)" :key="d.id" class="text-action linked-source" @click="nav({decision:d.id})">{{ d.chosen }} →</button><details class="record-followup"><summary>Specification revision history</summary><article v-for="h in [...selectedSection.history].reverse()" :key="h.revision" class="linked-record"><b>r{{ h.revision }} · {{ h.note }}</b><p class="small muted">@{{ handleOf(h.byMemberId) }} · {{ new Date(h.at).toLocaleString() }}</p><details><summary>Read this revision</summary><Markdown :source="h.content.body" /><p>Source decisions: {{ h.content.decisionIds.map(id=>decisions.find(d=>d.id===id)?.chosen ?? id).join('; ') }}</p></details></article></details></template>
          <p v-else class="empty-note">No specification has been written for this subsystem. Its adopted decisions are below; combine them into a reviewed document when ready.</p>
        </article>
      </template>
      <div class="section-heading"><h3>{{ history ? 'Decision history' : 'Adopted decisions' }}</h3><span>{{ visible.length }}</span></div><p v-if="!visible.length" class="empty-note">No matching decisions. Design adoption happens when the lead reviews a discussion’s draft outcome.</p><div class="decision-list"><button v-for="d in visible" :key="d.id" class="record-row" @click="nav({decision:d.id})"><span class="eyebrow">{{ decisionSystem(d) }} · {{ current.some(x=>x.id===d.id) ? 'Current' : 'Superseded' }}</span><strong>{{ d.chosen }}</strong><span class="small muted">@{{ handleOf(d.byMemberId) }} · {{ new Date(d.at).toLocaleDateString() }} · {{ grants.filter(g=>g.decisionIds?.includes(d.id)).length }} linked work packages</span><span>Read decision →</span></button></div>
      <section v-if="history" class="other-outcomes"><h3>Other recorded outcomes</h3><article v-for="b in bundles.filter(b => (b.thread.versionId === version.id || b.thread.deferrals.some(d=>d.fromVersionId===version.id)) && (!system || (b.thread.system ?? 'project-wide') === system) && b.thread.title.toLowerCase().includes(search.toLowerCase()) && (b.thread.resolution?.kind === 'reject' || (b.thread.resolution?.kind === 'conclude' && !b.thread.resolution.decisionId) || b.thread.deferrals.length))" :key="b.thread.id" class="linked-record"><span class="eyebrow">{{ b.thread.resolution?.kind === 'reject' ? 'Not pursuing' : b.thread.status === 'open' ? 'Deferred' : 'Conclusion · no design change' }}</span><h4>{{ b.thread.title }}</h4><p v-if="b.thread.resolution?.kind === 'reject'">{{ b.thread.resolution.note }}</p><button class="text-action" @click="emit('navigate','shape',{thread:b.thread.id,version:b.thread.versionId,tab:'draft'})">Read outcome →</button></article></section>
    </template>
  </section>
</template>
