// Seed SQL for the shared Supabase: the starting threads, positions and
// replies from src/modules/threads/data.ts, with people named in notes kept
// as `named` (they have no account rows). Idempotent: existing ids are left alone.
//   npx tsx scripts/build-seed-sql.ts > supabase/seed_quiver.sql
import { threads } from '../src/modules/threads/data';

const q = (v: unknown) => (v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v: unknown) => (v === undefined || v === null ? 'null' : `${q(JSON.stringify(v))}::jsonb`);
const out: string[] = ['-- Generated by scripts/build-seed-sql.ts. Do not edit by hand.', 'begin;'];
for (const t of threads) {
  out.push(
    `insert into public.sa_threads (id, zone, part, pcb, title, body, type, kind, system, version, named, source, raised_at, active_at, settled, declined, deferrals) values (${[
      q(t.id), q(t.zone), q(t.part), j(t.pcb), q(t.title), q(t.body), q(t.type), q(t.kind), `'${t.system.replace(/'/g, "''")}'`, `'${(t.version ?? '').replace(/'/g, "''")}'`, q(t.authorId), j(t.source),
      q(t.raisedAt), q(t.activeAt), j(t.settled), j(t.declined), j(t.deferrals ?? []),
    ].join(', ')}) on conflict (id) do nothing;`,
  );
  t.positions.forEach((p, i) => {
    out.push(`insert into public.sa_positions (id, thread_id, text, named, source, ord, created_at) values (${[q(`${t.id}-${p.id}`), q(t.id), q(p.text), q(p.authorId), j(p.source), i, q(p.at)].join(', ')}) on conflict (id) do nothing;`);
  });
  for (const r of t.replies) {
    out.push(`insert into public.sa_replies (id, thread_id, text, named, source, created_at) values (${[q(`${t.id}-${r.id}`), q(t.id), q(r.text), q(r.authorId), j(r.source), q(r.at)].join(', ')}) on conflict (id) do nothing;`);
  }
}
// Seeded decisions point at seeded position ids, which are prefixed in the database.
out.push(`update public.sa_threads set settled = jsonb_set(settled, '{positionId}', to_jsonb(id || '-' || (settled->>'positionId'))) where settled is not null and settled->>'positionId' not like 'Q-%';`);
const maxThread = Math.max(...threads.map((t) => Number(t.id.slice(2))));
const decisions = threads.filter((t) => t.settled).length;
out.push(`update public.sa_counters set value = greatest(value, ${maxThread}) where name = 'thread';`);
out.push(`update public.sa_counters set value = greatest(value, ${decisions}) where name = 'decision';`);
out.push('commit;');
console.log(out.join('\n'));
