const {chromium}=require('playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.BASE_URL||'http://localhost:4190/';const OUT='/tmp/arrow-briefing-review';fs.mkdirSync(OUT,{recursive:true});let checks=0;
function check(name,value){assert.ok(value,name);console.log('PASS '+name);checks++;}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async(q='')=>{await page.goto(BASE+'#/p/spearhead?'+q);await page.locator('.project-workspace').waitFor()};const button=(name)=>page.getByRole('button',{name,exact:true});const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('arrow-spec-threads-demo-v2')));
try {
await go();await page.locator('.project-overview').waitFor();check('overview is the default project home',await button('Overview').getAttribute('aria-current')==='page');check('review attention names the actual submission',(await page.locator('.attention-panel').innerText()).includes('keyed connector assembly guide'));await page.screenshot({path:OUT+'/overview-desktop.png',fullPage:true});
await page.locator('.story-card').filter({has:page.getByText('avionics',{exact:true})}).click();await page.getByRole('heading',{name:'Now & next',exact:true}).waitFor();check('subsystem joins current design with active work',(await page.locator('.project-overview').innerText()).includes('Physically key incompatible harness interfaces')&&(await page.locator('.project-overview').innerText()).includes('Build the keyed avionics harness'));check('accepted test result is traceable to the new decision',await page.getByRole('button',{name:'Informed by results: Glove-on harness fit check →'}).isVisible());await page.screenshot({path:OUT+'/avionics-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Informed by results: Glove-on harness fit check →'}).click();await page.locator('.work-tracker').waitFor();check('source result opens completed work',await page.locator('.accepted-evidence').isVisible());check('completed controls are collapsed',!(await page.locator('.work-control-panel').evaluate(e=>e.open)));
await go('view=work');await page.locator('.work-row').first().waitFor();check('default work contains only seven active items',await page.locator('.work-row').count()===7);check('filters start hidden',!(await page.getByLabel('Work type filter').isVisible()));check('zero milestone clutter is gone',!(await page.locator('.work-view').innerText()).includes('0/0 milestones'));
await page.getByRole('button',{name:'Needs review 1',exact:true}).click();check('review queue isolates the pending submission',await page.locator('.work-row').count()===1);await page.locator('.work-row').click();await page.locator('.work-tracker').waitFor();check('review detail starts with readable criteria and submitted evidence',await page.getByRole('heading',{name:'What completion needs to show'}).isVisible()&&await page.locator('.accepted-evidence').isVisible());check('review detail is not an edit form by default',!(await page.getByLabel('Work status',{exact:true}).isVisible()));await page.screenshot({path:OUT+'/review-desktop.png',fullPage:true});await button('Review submission').click();check('relevant next action reveals review controls',await page.getByLabel('Work status',{exact:true}).isVisible());await page.getByRole('checkbox',{name:'Accepted by lead',exact:true}).check();await page.getByLabel('Work status',{exact:true}).selectOption('completed');await page.getByLabel('Work update note').fill('Reviewed the illustrated strain-relief correction.');await button('Save work update').click();await page.getByRole('status').filter({hasText:'Work update saved.'}).waitFor();
await go();await page.locator('.project-overview').waitFor();check('briefing updates when a submission is accepted',!(await page.locator('.attention-panel').innerText()).includes('keyed connector assembly guide'));
await go('view=work&queue=history');await page.locator('.work-row').first().waitFor();check('completed submission moves into history',await page.locator('.work-row').count()===4);await go('view=work&queue=all');await page.locator('.work-row').first().waitFor();check('all work still exposes all ten records',await page.locator('.work-row').count()===10);await button('Filter').click();await page.getByLabel('Work type filter').selectOption('bounty');check('advanced filters still work',await page.locator('.work-row').count()===5);await page.getByRole('button',{name:'Filter · 1'}).click();check('hidden applied filters retain a visible count',await page.getByRole('button',{name:'Filter · 1'}).isVisible());await button('Clear filters').click();check('clear restores the full list',await page.locator('.work-row').count()===10);
await go('view=work&queue=open');await page.locator('.work-row').first().waitFor();check('opportunities surface scope funding and only unassigned open work',await page.locator('.work-row').count()===2&&(await page.locator('.work-list').innerText()).includes('proposed'));
await page.getByLabel('Demo persona').selectOption('m-jun');await go('view=work&queue=mine');await page.locator('.work-row').first().waitFor();check('my work is tied to the current person',await page.locator('.work-row').count()===1&&(await page.locator('.work-row').innerText()).includes('keyed avionics harness'));
await page.getByLabel('Demo persona').selectOption('');await page.getByText('Choose a persona to see your work.',{exact:true}).waitFor();check('signed-out view does not invent assignments',await page.locator('.work-row').count()===0);await page.getByLabel('Demo persona').selectOption('m-omar');
await go('view=work&grant=sample-delivery-power-fixture');await page.locator('.work-tracker').waitFor();check('draft scope is read-first',await button('Edit scope').isVisible()&&!(await page.getByLabel('Scope (markdown)',{exact:true}).isVisible()));await button('Edit scope').click();await page.getByLabel('Scope (markdown)',{exact:true}).fill('A saved clarity-test scope.');await button('Save draft').click();await button('Edit scope').waitFor();check('scope save returns to reading',await page.locator('.scope-card').getByText('A saved clarity-test scope.',{exact:true}).isVisible());
await go('view=design&system=avionics');await page.locator('.specification-document').waitFor();check('subsystem view does not show unrelated pending decisions',!(await page.locator('.design-view').innerText()).includes('not yet included in the specification'));check('current specification is primary',await page.locator('.specification-document').isVisible()&&!(await page.locator('.adopted-register').evaluate(e=>e.open)));await page.getByText('Decisions behind the design · 1',{exact:true}).click();check('adopted decisions remain accessible',await page.locator('.decision-list').isVisible());
for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const [name,q,selector] of [['overview','','.project-overview'],['avionics','system=avionics','.project-overview'],['work','view=work','.work-list'],['review','view=work&grant=sample-delivery-keyed-review','.work-tracker'],['design','view=design&system=avionics','.specification-document']]){await go(q);await page.locator(selector).waitFor();check(name+' fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390)await page.screenshot({path:OUT+'/'+name+'-mobile.png',fullPage:true});}}
await page.reload();await page.locator('.specification-document').waitFor();check('user changes persist through new navigation and reload',(await data()).grants.find(g=>g.id==='sample-delivery-power-fixture').scope==='A saved clarity-test scope.');
await go('version=sh-pt1');await page.locator('.project-overview').waitFor();check('overview respects the selected baseline',await page.getByLabel('Project version').inputValue()==='sh-pt1'&&!(await page.locator('.attention-panel').innerText()).includes('keyed connector'));await page.goto(BASE+'#/p/quiver');await page.locator('.project-overview').waitFor();check('quiet projects have honest empty states',(await page.locator('.project-overview').innerText()).includes('No work is in progress'));
check('no browser errors',errors.length===0);console.log(`${checks} briefing browser checks passed.`);
}catch(e){console.error(errors);await page.screenshot({path:OUT+'/failure.png',fullPage:true});throw e}finally{await browser.close()}})();
