const {chromium}=require('playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.BASE_URL||'http://localhost:4188/';
const SHOTS='/tmp/arrow-records-review';fs.mkdirSync(SHOTS,{recursive:true});
let checks=0;function check(name,yes){assert.ok(yes,name);console.log('PASS '+name);checks++;}
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await require('./minimal-fixture.cjs').minimalFixture(page, BASE);
 const go=async(q)=>{await page.goto(BASE+'#/p/spearhead?'+q)};
 const button=(name)=>page.getByRole('button',{name,exact:true});
 const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('arrow-spec-threads-demo-v2')));
 const update=async(note)=>{await page.getByLabel('Work update note',{exact:true}).fill(note);await button('Save work update').click();await page.getByRole('status').filter({hasText:'Work update saved.'}).waitFor()};
 try{
  await go('view=shape&thread=n-engine&tab=draft');await button('Edit draft').click();await page.getByLabel('Draft document',{exact:true}).fill('## Engine interface\n\nProvide telemetry and independent shutdown.\n\nThis is an illustrative bench prototype, not a flight-approved design.');await page.getByLabel('Unresolved questions',{exact:true}).fill('');await button('Save draft').click();await page.getByText('Draft saved.',{exact:true}).waitFor();await page.getByRole('checkbox',{name:'Adopt into the design'}).check();await page.getByRole('checkbox',{name:'Commission work'}).check();await page.getByLabel('Work format',{exact:true}).selectOption('grant');await page.getByLabel('Work title',{exact:true}).fill('Engine interface bench prototype');await page.getByLabel('Work scope',{exact:true}).fill('Deliver a schematic and bench board.');await page.getByLabel('Work acceptance criteria',{exact:true}).fill('Show shutdown without the flight controller.');await page.getByRole('checkbox',{name:/I’ve reviewed/}).check();await button('Approve and record outcome').click();await page.getByText('What we concluded',{exact:true}).waitFor();
  const seeded=await data(),decision=seeded.decisions.find(d=>d.threadId==='n-engine'),grant=seeded.grants[0];
  await button('Design').click();await page.locator('.design-view').waitFor();check('Design is a first-class project home',await page.getByRole('navigation',{name:'Design views'}).isVisible());check('unintegrated decisions are explicit',await page.getByText(/adopted decisions not yet included/).isVisible());
  await page.getByLabel('Design subsystem').selectOption('propulsion');await button('Write specification').click();await page.getByLabel('Specification document',{exact:true}).fill('## Engine interface requirements\n\nTelemetry must be available on the bus. Shutdown must remain independent of the flight controller.\n\n## Cross-system constraint\n\nRetain the agreed transport envelope.');await page.getByRole('checkbox',{name:'Cap the span at 3.0 m'}).check();await page.getByLabel('Specification revision note').fill('Combine propulsion and airframe constraints.');await button('Save reviewed specification').click();await button('Revise specification').waitFor();check('one specification combines multiple discussions',(await data()).specifications[0].decisionIds.length===2);await page.screenshot({path:SHOTS+'/specification-desktop.png',fullPage:true});
  await button('Revise specification').click();await page.getByLabel('Specification document',{exact:true}).fill('Unsaved replacement');page.once('dialog',d=>d.dismiss());await button('Work 1').click();check('unsaved specification blocks accidental navigation',await page.getByLabel('Specification document',{exact:true}).isVisible());page.once('dialog',d=>d.accept());await button('Cancel').click();
  await button('Revise specification').click();await page.getByLabel('Specification document',{exact:true}).fill('## Engine interface requirements\n\nTelemetry and independent shutdown. Bench validation required.\n\nRetain the agreed transport envelope.');await page.getByLabel('Specification revision note').fill('Add explicit validation.');await button('Save reviewed specification').click();await button('Revise specification').waitFor();await page.getByText('Specification revision history',{exact:true}).click();check('specification revision history retains old content',(await data()).specifications[0].history[0].content.body.includes('Cross-system constraint'));
  await page.locator('.linked-source').filter({hasText:decision.chosen}).click();await page.locator('.decision-detail').waitFor();check('decision links its commissioned work',await page.getByRole('button',{name:'Engine interface bench prototype →',exact:true}).isVisible());await button('Engine interface bench prototype →').click();await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();check('work detail is linked to Design and original discussion',await page.getByRole('link',{name:'Read the recorded outcome'}).isVisible());
  await page.getByLabel('Assigned owner',{exact:true}).selectOption('m-jun');await page.getByLabel('Work status',{exact:true}).selectOption('open');await page.getByLabel('Funding status',{exact:true}).selectOption('funded');await page.getByLabel('Budget / currency',{exact:true}).fill('2,000 USDC');await page.getByLabel('Due date',{exact:true}).fill('2026-10-15');await button('Add milestone').click();await page.getByLabel('Milestone 1 title',{exact:true}).fill('Schematic review');await page.getByLabel('Milestone 1 acceptance',{exact:true}).fill('Verify telemetry and independent shutdown interfaces.');await update('Opened and funded; Jun owns delivery.');check('opening work persists assignment and separate funding',(await data()).grants[0].tracking.stage==='open'&&(await data()).grants[0].tracking.funding==='funded');
  await page.getByLabel('Demo persona').selectOption('m-jun');await page.waitForFunction(()=>document.querySelector('[aria-label="Assigned owner"]').disabled);check('owner cannot change assignment or funding',await page.getByLabel('Funding status',{exact:true}).isDisabled());await page.getByLabel('Work status',{exact:true}).selectOption('in_progress');await update('Started board design.');await page.getByLabel('Work status',{exact:true}).selectOption('in_review');await page.getByLabel('Work update note',{exact:true}).fill('Ready for review.');await button('Save work update').click();await page.getByRole('alert').filter({hasText:'Attach result evidence'}).waitFor();check('review rejects missing evidence',(await data()).grants[0].tracking.stage==='in_progress');await page.getByRole('button',{name:'Dismiss',exact:true}).click();await page.getByLabel('Result evidence',{exact:true}).fill('## Bench report\n\nIndependent shutdown passed with the FC disconnected. Schematic and test log attached to the review.');await page.getByLabel('Milestone 1 evidence',{exact:true}).fill('Interface checklist reviewed; bench test log recorded.');await update('Submitted schematic and bench report.');check('owner submits for review but cannot accept completion',!(await page.getByLabel('Work status',{exact:true}).locator('option').allTextContents()).includes('Completed'));
  await page.getByLabel('Demo persona').selectOption('m-omar');await page.waitForFunction(()=>!document.querySelector('[aria-label="Assigned owner"]').disabled);await page.getByRole('checkbox',{name:'Accepted by lead',exact:true}).check();await page.getByLabel('Work status',{exact:true}).selectOption('completed');await update('Reviewed the evidence against every acceptance criterion.');check('lead completion preserves funding as funded, not paid',(await data()).grants[0].tracking.stage==='completed'&&(await data()).grants[0].tracking.funding==='funded');check('accepted results are visible',await page.getByText('ACCEPTED RESULTS',{exact:true}).isVisible());await page.screenshot({path:SHOTS+'/work-completed-desktop.png',fullPage:true});
  await page.locator('.work-tracker .linked-source').click();await page.locator('.decision-detail').waitFor();await page.getByText('Read work evidence',{exact:true}).click();check('accepted work evidence appears on the linked decision',(await page.locator('.decision-detail').innerText()).includes('Independent shutdown passed'));
  await button('Engine interface bench prototype →').click();await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();await page.getByText('Start a linked follow-up discussion',{exact:true}).click();await page.getByLabel('Finding or question',{exact:true}).fill('The bench report suggests we should revise the input protection.');await button('Start follow-up').click();await page.locator('.discussion-conversation').waitFor();check('test finding returns to one linked conversation',page.url().includes('view=shape')&&(await data()).threads.some(t=>t.sourceGrantId===grant.id));check('follow-up preserves accepted result',(await data()).grants[0].tracking.stage==='completed');await page.getByRole('link',{name:'a work result',exact:true}).click();await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();check('follow-up source link returns to work',page.url().includes(grant.id));
  await go('view=work&queue=all');await page.locator('.work-row').waitFor();await button('Filter').click();await page.getByLabel('Work type filter').selectOption('bounty');check('type filter separates grants and bounties',await page.locator('.work-row').count()===0);await page.getByLabel('Work type filter').selectOption('');await page.getByLabel('Work status filter').selectOption('completed');check('completion filter finds accepted work',await page.locator('.work-row').count()===1);await page.getByLabel('Owner filter').selectOption('m-rosa');check('owner filter is applied',await page.locator('.work-row').count()===0);await page.getByLabel('Owner filter').selectOption('m-jun');await page.getByLabel('Funding filter').selectOption('paid');check('funding filter does not confuse completion with payment',await page.locator('.work-row').count()===0);await page.getByLabel('Funding filter').selectOption('funded');check('funded filter finds unpaid completed work',await page.locator('.work-row').count()===1);await page.screenshot({path:SHOTS+'/work-list-desktop.png',fullPage:true});
  for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});for(const q of ['view=design','view=design&system=propulsion','view=work','view=work&grant='+grant.id]){await go(q);await page.locator('.records-view').waitFor();if(q.includes('grant='))await page.locator('.work-tracker').waitFor();check('no overflow '+width+' '+q.split('&grant=')[0],await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(width===390){await page.screenshot({path:SHOTS+'/work-mobile.png',fullPage:true});await go('view=design&system=propulsion');await page.locator('.specification-document').waitFor();await page.screenshot({path:SHOTS+'/specification-mobile.png',fullPage:true});}}
  await page.reload();await page.locator('.specification-document').waitFor();check('specification and work persist across reload',(await data()).specifications[0].revision===2&&(await data()).grants[0].tracking.stage==='completed');
  await page.setViewportSize({width:1440,height:1050});
  await go('view=design&decision=d-wingspan');await button('Commission work from this outcome →').click();await page.getByLabel('Reviewed source outcome',{exact:true}).waitFor();check('commissioning from Design prefills the source and scope',(await page.getByLabel('Reviewed source outcome',{exact:true}).inputValue())==='n-wingspan'&&(await page.getByLabel('Work scope',{exact:true}).inputValue()).length>0);await page.getByLabel('Work format',{exact:true}).selectOption('bounty');await page.getByLabel('Work title',{exact:true}).fill('Transport envelope verification');await page.getByLabel('Work acceptance criteria',{exact:true}).fill('Record the transport fit check.');await button('Create work draft').click();await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();check('legacy decisions can commission work without reopening discussion',(await data()).grants.some(g=>g.title==='Transport envelope verification'));
  const transport=(await data()).grants.find(g=>g.title==='Transport envelope verification');
  await page.getByLabel('Work status',{exact:true}).selectOption('open');await page.getByLabel('Assigned owner',{exact:true}).selectOption('m-rosa');await update('Ready for transport fit check.');
  await go('view=work');await button('Filter').click();await page.getByLabel('Work type filter').selectOption('bounty');check('grant and bounty share a work home with distinct type',await page.locator('.work-row').count()===1&&(await page.locator('.work-row').innerText()).includes('Transport envelope'));
  for(const t of (await data()).threads.filter(t=>t.projectId==='spearhead'&&t.versionId==='sh-pt2'&&t.status==='open')){
    await go('view=shape&tab=draft&version=sh-pt2&thread='+t.id);await button('Start a draft').click();await page.getByLabel('Draft document',{exact:true}).fill('Record the findings; no additional design change in this baseline.');await button('Save draft').click();await page.getByText('Draft saved.',{exact:true}).waitFor();await page.getByRole('checkbox',{name:/I’ve reviewed/}).check();await button('Record conclusion').click();await page.getByText('What we concluded',{exact:true}).waitFor();
  }
  await go('view=review&version=sh-pt2');page.once('dialog',d=>d.accept());await button('Freeze PT2 design').click();await page.getByText('PT2 is ready for the next chapter.',{exact:true}).waitFor();await go('view=design&version=sh-pt2&system=propulsion');await page.locator('.specification-document').waitFor();check('frozen specification is readable but not editable',await button('Revise specification').count()===0&&(await page.locator('.specification-document').innerText()).includes('Bench validation required'));
  await go('view=work&version=sh-pt2&grant='+transport.id);await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();await page.getByLabel('Work status',{exact:true}).selectOption('in_progress');await update('Started after design freeze.');check('work progresses against a frozen design',(await data()).grants.find(g=>g.id===transport.id).tracking.stage==='in_progress');
  await go('view=work&version=sh-pt3&queue=all');await button('Filter').click();await page.locator('.work-filters').waitFor();check('version filter separates next design from earlier work',await page.locator('.work-row').count()===0);await page.getByRole('checkbox',{name:'All versions',exact:true}).check();await page.locator('.work-row').first().waitFor();check('all-versions work keeps the previous build visible',await page.locator('.work-row').count()===2);
  await go('view=design&version=sh-pt3&decision='+decision.id);await page.getByText('Start a linked follow-up discussion',{exact:true}).click();await page.getByLabel('Finding or question',{exact:true}).fill('New test evidence changes the interface.');await button('Start follow-up').click();await page.locator('.discussion-conversation').waitFor();const newer=(await data()).threads.find(t=>t.sourceDecisionId===decision.id);check('new design discussion targets the next version',newer.versionId==='sh-pt3');
  await go('view=shape&tab=draft&version=sh-pt3&thread='+newer.id);await button('Start a draft').click();await page.getByLabel('Draft document',{exact:true}).fill('Revised input protection and independent shutdown.');await button('Save draft').click();await page.getByText('Draft saved.',{exact:true}).waitFor();await page.getByRole('checkbox',{name:'Adopt into the design'}).check();await page.getByRole('checkbox',{name:/I’ve reviewed/}).check();await button('Approve and record outcome').click();await page.getByText('What we concluded',{exact:true}).waitFor();const replacement=(await data()).decisions.find(d=>d.threadId===newer.id);
  await go('view=design&version=sh-pt3&decision='+replacement.id);await page.getByText('This decision replaces an earlier choice',{exact:true}).click();await page.getByRole('checkbox',{name:decision.chosen,exact:true}).check();await page.getByLabel('Reason for replacement',{exact:true}).fill('New bench evidence.');await button('Record replacement').click();await page.getByText('Replaces earlier decisions',{exact:true}).waitFor();check('replacement preserves original adopted document',(await data()).decisions.find(d=>d.id===decision.id).outcomeSnapshot.body===decision.outcomeSnapshot.body);
  await go('view=design&version=sh-pt3&system=propulsion');await page.getByText(/source decision has been replaced/).waitFor();check('inherited specification flags replaced sources',await page.getByText(/needs updating/).isVisible());await button('Revise specification').click();await page.getByLabel('Specification document',{exact:true}).fill('PT3: revised protection and shutdown.');await page.getByRole('checkbox',{name:replacement.chosen,exact:true}).check();await page.getByLabel('Specification revision note').fill('Integrate new bench findings.');await button('Save reviewed specification').click();await button('Revise specification').waitFor();
  await go('view=design&version=sh-pt2&system=propulsion');await page.locator('.specification-document').waitFor();check('later specification revision cannot rewrite frozen baseline',!(await page.locator('.specification-document').innerText()).includes('PT3: revised'));
  await page.getByLabel('Demo persona').selectOption('m-ade');await page.waitForTimeout(100);check('non-lead cannot revise specification',await button('Revise specification').count()===0);await page.getByLabel('Demo persona').selectOption('');await go('view=work&grant='+grant.id);await page.locator('.work-tracker').waitFor();await page.locator('.work-control-panel > summary').click();if(await page.getByText('Why this work exists',{exact:true}).count())await page.getByText('Why this work exists',{exact:true}).click();check('signed-out viewer can read but not update',await button('Save work update').count()===0);check('no browser errors',errors.length===0);
  console.log(`${checks} design/work browser checks passed. Screenshots: ${SHOTS}`);
 }catch(e){console.error(errors);await page.screenshot({path:SHOTS+'/failure.png',fullPage:true});throw e;}finally{await browser.close()}
})();
