const {chromium}=require('playwright-core');const assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.BASE_URL||'http://10.3.10.123:4193/';const OUT='/tmp/spearhead-real-review';fs.mkdirSync(OUT,{recursive:true});let count=0;const check=(name,value)=>{assert.ok(value,name);count++;console.log('PASS '+name)};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const go=async(q)=>{await page.goto(BASE+'#/p/spearhead?'+q);await page.locator('.sourced-workspace').waitFor()};try{
await go('view=sources&evidence=review');check('all 16 documentation-review items visible',await page.locator('.repo-review-panel .repo-follow-item').count()===16);const counts=await page.locator('.repo-review-counts').innerText();check('coverage counts do not claim 16 formal approvals',counts.includes('1\nRecorded in repo')&&counts.includes('2\nPartly recorded')&&counts.includes('8\nNo repo record found')&&counts.includes('5\nNeeds reconciliation')&&(await page.locator('.repo-review-panel').innerText()).includes('not 16 approved design decisions'));
await go('view=sources');const wikiCards=page.locator('.sourced-source-grid article').filter({has:page.locator('a[href*="/wiki/"]')});check('wiki sources are labeled call summaries',await wikiCards.count()>0&&await wikiCards.locator('.eyebrow').filter({hasText:'Call summary · Vector'}).count()===await wikiCards.count());
await go('view=sources&evidence=review');const item=title=>page.locator('.repo-review-panel .repo-follow-item').filter({has:page.locator('summary strong',{hasText:title})});
await item('Dummy-board pack first; BMS provision later').locator('summary').focus();await page.keyboard.press('Enter');check('keyboard expands scope qualification',(await item('Dummy-board pack first; BMS provision later').innerText()).includes('does not establish a kill-switch violation'));
await item('Dated PT1 electrical decision register').locator('summary').click();check('recorded register keeps D3 partially open',(await item('Dated PT1 electrical decision register').innerText()).includes('D3 is only partially closed'));
await item('Use GitHub Discussions for open topics').locator('summary').click();check('current Discussions state is not invented history',(await item('Use GitHub Discussions for open topics').innerText()).includes('cannot establish that Discussions was never enabled'));
await item('14S Longshot and AS150U for PT2').locator('summary').click();check('voltage scopes remain distinct',(await item('14S Longshot and AS150U for PT2').innerText()).includes('does not erase PT1'));
await page.screenshot({path:OUT+'/repo-review-desktop.png',fullPage:true});
await item('14S Longshot and AS150U for PT2').getByRole('button',{name:/A 14S3P Longshot variant for Spearhead/}).click();await page.getByRole('heading',{name:'A 14S3P Longshot variant for Spearhead',exact:true}).waitFor();check('review links back to existing project record',await page.locator('.repo-detail-review').isVisible());check('repository follow-through does not replace call-agreement status',await page.locator('.briefing-heading [data-status="agreed"]').isVisible());await page.locator('.repo-detail-review summary').filter({hasText:'14S Longshot'}).click();check('record sidebar shows version-scoped reconciliation',(await page.locator('.repo-detail-review').innerText()).includes('12S/QS8-S document describes PT1'));
await go('view=shape&record=electric-first');check('tentative propulsion remains a proposal',await page.locator('.briefing-heading [data-status="proposal"]').isVisible());
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const q of ['view=sources&evidence=review','view=design&record=dual-battery']){await go(q);if(q.includes('record'))await page.locator('.repo-detail-review summary').click();else await item('Dummy-board pack first; BMS provision later').locator('summary').click();check('repository review fits '+width+' '+q,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390&&q.includes('record'))await page.screenshot({path:OUT+'/repo-review-detail-mobile.png',fullPage:true});}}
check('no browser runtime errors',errors.length===0);console.log(count+' repository-review browser checks passed');}catch(e){await page.screenshot({path:OUT+'/repo-review-failure.png',fullPage:true});throw e}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
