const {chromium}=require('playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
const BASE=process.env.BASE_URL||'http://localhost:4187/';const OUT='/tmp/arrow-samples-review';fs.mkdirSync(OUT,{recursive:true});let checks=0;
function check(name,condition){assert.ok(condition,name);console.log('PASS '+name);checks++;}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const go=async(q)=>{await page.goto(BASE+'#/p/spearhead?'+q)};const button=name=>page.getByRole('button',{name,exact:true});const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('arrow-spec-threads-demo-v2')));
try{
 await go('view=work&queue=all');await page.locator('.work-row').first().waitFor();await button('Filter').click();check('fresh demo has ten work packages',await page.locator('.work-row').count()===10);check('original engine conversation remains open',(await data()).threads.find(t=>t.id==='n-engine').status==='open');await page.screenshot({path:OUT+'/work-desktop.png',fullPage:true});
 for(const [stage,count]of Object.entries({draft:1,open:2,in_progress:3,in_review:1,completed:2,cancelled:1})){await page.getByLabel('Work status filter').selectOption(stage);check('sample stage '+stage,await page.locator('.work-row').count()===count)}
 await page.getByLabel('Work status filter').selectOption('completed');await page.getByLabel('Funding filter').selectOption('funded');check('completed-but-unpaid example is distinct',await page.locator('.work-row').count()===1&&(await page.locator('.work-row').innerText()).includes('Wing retention'));
 await page.getByLabel('Funding filter').selectOption('paid');check('separate paid example is visible',await page.locator('.work-row').count()===1&&(await page.locator('.work-row').innerText()).includes('fit check'));
 await page.getByLabel('Funding filter').selectOption('');await page.getByLabel('Work status filter').selectOption('');await page.getByLabel('Work type filter').selectOption('grant');check('grant filter finds five grants',await page.locator('.work-row').count()===5);await page.getByLabel('Work type filter').selectOption('bounty');check('bounty filter finds five bounties',await page.locator('.work-row').count()===5);
 await go('view=design&system=avionics');await page.locator('.specification-document').waitFor();check('avionics has a readable specification',(await page.locator('.specification-document').innerText()).includes('physically keyed'));
 await page.getByText('Specification revision history',{exact:true}).click();check('specification shows pre- and post-test revisions',(await page.locator('.specification-document').innerText()).includes('Reconciled connector choice'));await page.screenshot({path:OUT+'/design-desktop.png',fullPage:true});
 await page.locator('.specification-document .linked-source').click();await page.locator('.decision-detail').waitFor();check('new connector decision explains its replacement',(await page.locator('.decision-detail').innerText()).includes('Replaces earlier decisions'));
 await page.getByRole('button',{name:'Common-shell harness with permanent labels →',exact:true}).click();await page.locator('.decision-detail').waitFor();check('superseded decision remains readable',(await page.locator('.decision-detail').innerText()).includes('SUPERSEDED DECISION'));
 await button('Glove-on harness fit check →').click();await page.locator('.work-tracker').waitFor();check('accepted evidence can report a design failure',(await page.locator('.accepted-evidence').innerText()).includes('design needs a change'));
 await button('Fit-check result: key the harness connectors →').click();await page.locator('.discussion-conversation').waitFor();check('completed work leads to its actual follow-up conversation',(await page.locator('.discussion-conversation').innerText()).includes('distinct physical keys'));
 await go('view=design&system=airframe');await page.locator('.specification-document').waitFor();check('airframe document combines two source decisions',await page.locator('.specification-document .linked-source').count()===2);
 await go('view=work&grant=sample-delivery-fuel-study');await page.locator('.work-tracker').waitFor();await page.getByText('Why this work exists',{exact:true}).click();await page.getByRole('link',{name:'Read the recorded outcome'}).click();await page.getByText('What we concluded',{exact:true}).waitFor();check('research has an outcome but no adopted design',(await page.locator('.outcome-result').innerText()).includes('no design change'));check('research retains its unanswered question',(await page.locator('.outcome-draft').innerText()).includes('Which approach remains useful'));
 await go('view=design&mode=history');await page.locator('.other-outcomes').waitFor();const history=(await page.locator('.other-outcomes').innerText()).toLowerCase();check('history includes rejection and plain conclusion',history.includes('sealed enclosure')&&history.includes('si units'));check('history includes deferred next-version discussion',history.includes('live fleet dashboard'));
 await go('view=shape&thread=sample-delivery-camera&tab=draft');await page.locator('.outcome-document').waitFor();check('an unfinished draft is ready for exploration',await button('Edit draft').isVisible()&&(await page.locator('.outcome-draft').innerText()).includes('Which motion measurement'));
 await go('view=work&grant=sample-delivery-keyed-review');await page.locator('.work-tracker').waitFor();await button('Review submission').click();await page.getByRole('checkbox',{name:'Accepted by lead',exact:true}).check();await page.getByLabel('Work status',{exact:true}).selectOption('completed');await page.getByLabel('Work update note').fill('Reviewed the replacement strain-relief photo; accept the guide.');await button('Save work update').click();await page.getByRole('status').filter({hasText:'Work update saved.'}).waitFor();check('sample awaiting-review work can actually be accepted',(await data()).grants.find(g=>g.id==='sample-delivery-keyed-review').tracking.stage==='completed');
 await page.reload();await page.locator('.work-tracker').waitFor();check('edited sample survives reload without reseeding',(await data()).grants.find(g=>g.id==='sample-delivery-keyed-review').tracking.stage==='completed'&&(await data()).grants.length===10);
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});for(const q of ['view=work','view=design&system=avionics']){await go(q);await page.locator('.records-view').waitFor();check('populated '+q+' fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390)await page.screenshot({path:OUT+(q.includes('design')?'/design-mobile.png':'/work-mobile.png'),fullPage:true})}}
 // Simulate a saved pre-upgrade demo in this isolated browser, with real user-edited fields.
 await page.evaluate(()=>{const key='arrow-spec-threads-demo-v2',s=JSON.parse(localStorage.getItem(key));for(const collection of ['threads','positions','comments','drafts','decisions','grants','specifications'])s[collection]=(s[collection]??[]).filter(row=>!(row.id??row.threadId).startsWith('sample-delivery-'));delete s.samplePacks;s.actingAs='m-rosa';s.threads.find(t=>t.id==='n-engine').body='KEEP MY EXISTING ENGINE NOTES';s.specifications=[{id:'user-airframe',projectId:'spearhead',versionId:'sh-pt2',system:'airframe',revision:4,body:'KEEP MY EXISTING SPECIFICATION',decisionIds:['d-wingspan'],updatedBy:'m-omar',updatedAt:'2026-09-25T12:00:00Z',history:[]}];localStorage.setItem(key,JSON.stringify(s))});
 await page.reload();await page.locator('.specification-document').waitFor();const upgraded=await data();check('old demo gains samples without a reset',upgraded.grants.length===10);check('existing conversation and persona survive',upgraded.threads.find(t=>t.id==='n-engine').body==='KEEP MY EXISTING ENGINE NOTES'&&upgraded.actingAs==='m-rosa');check('existing subsystem document wins over sample specification',upgraded.specifications.find(s=>s.system==='airframe').body==='KEEP MY EXISTING SPECIFICATION'&&upgraded.specifications.filter(s=>s.system==='airframe').length===1);
 await page.evaluate(()=>{const key='arrow-spec-threads-demo-v2',s=JSON.parse(localStorage.getItem(key));s.grants=s.grants.filter(g=>g.id!=='sample-delivery-logger');localStorage.setItem(key,JSON.stringify(s))});await page.reload();await page.locator('.specification-document').waitFor();check('deleted examples are not resurrected',(await data()).grants.length===9);check('no browser errors',errors.length===0);console.log(`${checks} sample browser checks passed.`);
}catch(e){console.error(errors);await page.screenshot({path:OUT+'/failure.png',fullPage:true});throw e}finally{await browser.close()}})();
