// Real-browser coverage of the project workspace's contribution → decision → freeze flow.
// Run against `npm run preview -- --port 4185`; browser state is isolated and discarded.
const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const BASE = process.env.BASE_URL || 'http://localhost:4185/';
const SHOTS = process.env.SHOTS_DIR || '/tmp/arrow-workspace-review';
fs.mkdirSync(SHOTS, { recursive: true });
let checks = 0;
function check(name, condition) { assert.ok(condition, name); console.log('PASS ' + name); checks++; }
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    const go = async hash => { await page.goto(BASE + '#' + hash); await page.waitForSelector('.workspace-tabs'); };
    const persona = async id => { await page.getByLabel('Demo persona').selectOption(id); };
    const review = async () => { await page.getByRole('button', { name: 'Design review', exact: true }).click(); await page.waitForSelector('.review-progress'); };
    const reviewRow = text => page.locator('.review-change', { hasText: text });
    const openDecision = async (text, kind) => {
      const row = reviewRow(text);
      await row.getByRole('button', { name: 'Make a decision' }).click();
      await row.locator('.btn-' + kind).click();
      return row;
    };
    await page.goto(BASE);
    await page.waitForSelector('.overview-hero');
    check('home lands inside Spearhead', page.url().includes('#/p/spearhead'));
    check('current build and next version are distinct', /PT1.*in the workshop.*PT2.*taking shape/.test((await page.locator('.version-timeline').innerText()).replace(/\s+/g, ' ')));
    check('overview counts come from the existing demo', (await page.locator('.brief-stats b').allTextContents()).join(',') === '3,1,7');
    await page.screenshot({ path: path.join(SHOTS, 'aircraft-desktop.png'), fullPage: true });
    await page.locator('.map-systems button').filter({ hasText: 'Propulsion' }).click();
    await page.waitForSelector('.discussion-panel');
    check('system map opens a filtered discussion in context', (await page.locator('.change-item').count()) === 1 && (await page.locator('.discussion-title').innerText()).includes('engine PCB'));
    await page.reload(); await page.waitForSelector('.discussion-title');
    check('system filter survives reload', (await page.locator('#system-filter').inputValue()) === 'propulsion');
    await persona('m-ade');
    await page.waitForFunction(() => !document.querySelector('.lead-disclosure'));
    check('non-leads cannot resolve a discussion', (await page.locator('.lead-disclosure').count()) === 0);
    const first = page.locator('.approach').first();
    await first.getByRole('button', { name: 'Support this approach', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.support-row .small')?.textContent.includes('+19.81'));
    check('support casts the existing weighted ballot', true);
    await first.getByRole('button', { name: 'Support this approach', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.support-row .small')?.textContent.includes('+18.81'));
    check('second click withdraws the ballot', true);
    await first.locator('input').fill('Verify the isolation barrier on the ignition output.');
    await first.getByRole('button', { name: 'Reply', exact: true }).click();
    await page.waitForSelector('.workspace-comment:has-text("Verify the isolation barrier")');
    check('reply lands on the selected approach', true);
    await page.locator('#approach-draft').fill('### Bench-test the kill input\n\nMeasure the response with the engine stopped. <svg onload="window.__xss=1"></svg>');
    await page.getByRole('button', { name: 'Add an approach' }).click();
    await page.waitForSelector('.approach-summary:has-text("Bench-test the kill input")');
    check('a new approach is added without losing the project', page.url().includes('/p/spearhead'));
    check('user markdown remains sanitized', await page.evaluate(() => !window.__xss && !document.querySelector('.discussion-panel .md [onload]')));
    await page.getByRole('button', { name: '+ I can help build this', exact: true }).click();
    await page.waitForSelector('button:has-text("✓ I can help build this")');
    check('builder interest remains functional', true);
    await page.getByRole('button', { name: 'Suggest a change', exact: false }).first().click();
    await page.waitForSelector('.compose-change');
    await page.getByLabel('Your question or proposed change').fill('Cooling access for maintenance');
    await page.getByLabel('Context', { exact: true }).fill('Can we inspect the cooling path without removing the engine?');
    await page.getByLabel('Aircraft system', { exact: true }).selectOption('propulsion');
    await page.getByLabel('Relevant expertise').fill('propulsion, Maintenance, maintenance');
    await page.getByRole('button', { name: 'Start discussion', exact: false }).click();
    await page.waitForSelector('.discussion-title:has-text("Cooling access")');
    check('new change targets PT2 and stays in the workspace', page.url().includes('version=sh-pt2') && page.url().includes('thread='));
    await page.reload(); await page.waitForSelector('.discussion-title:has-text("Cooling access")');
    check('new change and its deep link survive reload', true);
    await review();
    check('non-lead has a read-only design review', (await page.getByRole('button', { name: 'Make a decision' }).count()) === 0 && (await page.getByRole('button', { name: 'Freeze PT2 design' }).count()) === 0);
    await persona('m-omar');
    await page.waitForSelector('button:has-text("Freeze PT2 design")');
    check('freeze disabled while questions remain', await page.getByRole('button', { name: 'Freeze PT2 design' }).isDisabled());
    let row = await openDecision('Cooling access', 'reject');
    check('reject needs a meaningful explanation', await row.locator('.resolve-form button[type=submit]').isDisabled());
    await row.locator('.resolve-form textarea').fill('We will inspect the service layout before opening another design task.');
    await row.locator('.resolve-form button[type=submit]').click();
    await row.waitFor({ state: 'detached' });
    check('declined work leaves the review queue', true);
    row = await openDecision('Gasoline engine', 'grant');
    await row.locator('.resolve-form button[type=submit]').click();
    await page.waitForSelector('.grant-card');
    await page.locator('.grant-card').click();
    await page.waitForSelector('.workspace-grant');
    check('grant opens within the project design', page.url().includes('/p/spearhead') && page.url().includes('grant='));
    check('grant preserves extracted constraints and author share', (await page.locator('.workspace-grant textarea').nth(1).inputValue()).includes('DroneCAN') && (await page.getByLabel('Proposer share, percent').inputValue()) === '25');
    await page.locator('.workspace-grant input[type=text]').fill('Build the engine interface board');
    await page.getByLabel('Proposer share, percent').fill('30');
    await page.getByRole('button', { name: 'Save draft', exact: true }).click();
    await page.waitForSelector('text=Saved.');
    await page.reload(); await page.waitForSelector('.workspace-grant');
    check('grant edits persist', (await page.locator('.workspace-grant input[type=text]').inputValue()) === 'Build the engine interface board' && (await page.getByLabel('Proposer share, percent').inputValue()) === '30');
    await page.getByRole('button', { name: 'Publish', exact: true }).click();
    await page.waitForSelector('.workspace-grant .chip:has-text("published")');
    check('publishing locks the demo draft', await page.locator('.workspace-grant input[type=text]').isDisabled());
    await page.getByRole('button', { name: 'Back to PT2 design', exact: false }).click();
    row = await openDecision('Avionics carrier', 'spec');
    await row.locator('.resolve-form button[type=submit]').click();
    await page.waitForFunction(() => document.querySelectorAll('.decision-card:not(.grant-card)').length === 2);
    check('adoption joins the emerging design', true);
    row = await openDecision('Payload bay', 'defer');
    await row.locator('.resolve-form input[type=text]').fill('Need field feedback before fixing the interface.');
    await row.locator('.resolve-form button[type=submit]').click();
    await row.waitFor({ state: 'detached' });
    await page.waitForFunction(() => document.querySelector('.review-progress strong')?.textContent.includes('5 of 5'));
    check('all four dispositions count toward review completion', true);
    await page.screenshot({ path: path.join(SHOTS, 'review-desktop.png'), fullPage: true });
    await page.locator('.decision-history summary').click();
    check('deferral and rejection remain in the design history', (await page.locator('.decision-history').innerText()).includes('Carried forward to PT3') && (await page.locator('.decision-history').innerText()).includes('inspect the service layout'));
    page.once('dialog', d => d.accept());
    await page.getByRole('button', { name: 'Freeze PT2 design' }).click();
    await page.waitForSelector('h2:has-text("PT2 is ready for the next chapter")');
    check('freeze keeps the completed PT2 review visible', await page.getByLabel('Review version').inputValue() === 'sh-pt2');
    check('next contributions now target PT3', ((await page.locator('.version-timeline').innerText()).replace(/\s+/g, ' ')).includes('PT3'));
    await page.getByLabel('Review version').selectOption('sh-pt3');
    await page.getByRole('button', { name: 'Shape PT3', exact: false }).click();
    await page.waitForSelector('.discussion-title:has-text("Payload bay")');
    check('deferred discussion appears in PT3 with history', (await page.locator('.context-note').innerText()).includes('Carried forward from PT2'));
    await page.locator('.project-navigation a[href="#/p/quiver"]').click();
    await page.waitForSelector('.project-heading h1:has-text("Quiver")');
    await page.getByRole('button', { name: 'Find your way in' }).click();
    await page.waitForSelector('.discussion-title:has-text("Attachment interface")');
    check('switching projects does not leak Spearhead threads', (await page.locator('.change-item').count()) === 1 && !(await page.locator('.change-sidebar').innerText()).includes('Gasoline'));
    await persona('m-lena');
    await review();
    row = await openDecision('Attachment interface', 'spec');
    await row.locator('.pick-row', { hasText: 'Go big' }).locator('input').check();
    check('overriding weighted preference still requires rationale', await row.locator('.resolve-form button[type=submit]').isDisabled());
    await row.locator('.resolve-form textarea').fill('Prioritize heavy attachments in this version; the next revision can optimize mass.');
    await row.locator('.resolve-form button[type=submit]').click();
    await page.waitForSelector('.decision-card:has-text("Prioritize heavy attachments")');
    check('override reasoning is visible on the adopted design', true);
    await go('/p/quiver-mini'); await page.waitForSelector('.overview-hero');
    check('empty project has accurate counts', (await page.locator('.brief-stats b').allTextContents()).join(',') === '0,0,0');
    await page.getByRole('button', { name: 'Find your way in' }).click();
    await page.waitForSelector('.workspace-empty');
    check('empty project has a usable first-contribution path', await page.locator('.workspace-empty').getByRole('button', { name: 'Start a discussion', exact: true }).isVisible());
    await go('/p/spearhead?view=shape&version=sh-pt3'); await page.waitForSelector('.discussion-panel');
    await persona('');
    await page.waitForSelector('.context-note:has-text("Choose a demo persona")');
    check('signed-out users can read, but not contribute', (await page.locator('.new-approach').count()) === 0 && await page.getByRole('button', { name: 'Support this approach', exact: true }).first().isDisabled());
    await go('/p/spearhead?view=shape&version=sh-pt3&thread=does-not-exist');
    await page.waitForSelector('.workspace-empty');
    check('missing deep link does not silently show a different discussion', (await page.locator('.workspace-empty').innerText()).includes('isn’t in this view'));
    for (const width of [390, 768, 1024]) {
      await page.setViewportSize({ width, height: 900 });
      for (const view of ['', '?view=shape&version=sh-pt3', '?view=review&version=sh-pt2']) {
        await go('/p/spearhead' + view);
        await page.waitForSelector(view.includes('shape') ? '.discussion-panel' : view.includes('review') ? '.review-progress' : '.overview-hero');
        check(`no overflow at ${width}px in ${view || 'aircraft'}`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
        if (width === 390) await page.screenshot({ path: path.join(SHOTS, `mobile-${view.includes('shape') ? 'discussion' : view.includes('review') ? 'review' : 'aircraft'}.png`), fullPage: true });
      }
    }
    await page.setViewportSize({ width: 1440, height: 1050 });
    await go('/p/spearhead'); await page.waitForSelector('.overview-hero');
    page.once('dialog', d => d.accept());
    await page.getByRole('button', { name: 'Reset demo data', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.brief-stats b')?.textContent === '3');
    check('reset restores the original project and persona', (await page.getByLabel('Demo persona').inputValue()) === 'm-omar');
    check('no runtime or console errors', errors.length === 0);
    console.log(`${checks} workspace checks passed.`);
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
