// Seed SQL for the shared Supabase: a project's starting threads and their
// comment trees, with people named in notes kept as `named` (they have no
// account rows). Idempotent: existing ids are left alone.
//   npx tsx scripts/build-seed-sql.ts > supabase/seed_quiver.sql
//   npx tsx scripts/build-seed-sql.ts longshot > supabase/seed_longshot.sql
import { threads as quiverThreads } from '../src/modules/threads/data';
import { longshotThreads } from '../src/projects/longshot/threads';
import { planOf } from '../src/projects/plans';

const project = process.argv[2] ?? 'quiver';
const threads = project === 'longshot' ? longshotThreads : quiverThreads;
const plan = planOf(project);
// Quiver counts under 'thread' and 'decision'; other projects under 'thread:<id>' (20261010000000_sa_projects.sql).
const counter = (kind: string) => (project === 'quiver' ? kind : `${kind}:${project}`);

const q = (v: unknown) => (v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v: unknown) => (v === undefined || v === null ? 'null' : `${q(JSON.stringify(v))}::jsonb`);
const out: string[] = ['-- Generated by scripts/build-seed-sql.ts. Do not edit by hand.', 'begin;'];
for (const t of threads) {
  out.push(
    `insert into public.sa_threads (id, project, zone, part, pcb, title, body, type, kind, system, version, named, source, raised_at, active_at, settled, declined, deferrals) values (${[
      q(t.id), q(project), q(t.zone), q(t.part), j(t.pcb), q(t.title), q(t.body), q(t.type), q(t.kind), `'${t.system.replace(/'/g, "''")}'`, `'${(t.version ?? '').replace(/'/g, "''")}'`, q(t.authorId), j(t.source),
      q(t.raisedAt), q(t.activeAt), j(t.settled), j(t.declined), j(t.deferrals ?? []),
    ].join(', ')}) on conflict (id) do nothing;`,
  );
  // One comment tree: parents come before their replies in the array.
  let top = 0;
  for (const p of t.positions) {
    const ord = p.parentId ? 0 : top++;
    out.push(`insert into public.sa_positions (id, thread_id, parent_id, text, named, source, ord, created_at) values (${[q(`${t.id}-${p.id}`), q(t.id), p.parentId ? q(`${t.id}-${p.parentId}`) : 'null', q(p.text), q(p.authorId), j(p.source), ord, q(p.at)].join(', ')}) on conflict (id) do nothing;`);
  }
}
// Seeded decisions point at seeded position ids, which are prefixed in the database.
out.push(`update public.sa_threads set settled = jsonb_set(settled, '{positionId}', to_jsonb(id || '-' || (settled->>'positionId'))) where project = ${q(project)} and settled is not null and settled->>'positionId' not like id || '-%';`);
const maxThread = Math.max(0, ...threads.map((t) => Number(t.id.slice(plan.prefix.length + 1))));
const decisions = threads.filter((t) => t.settled).length;
out.push(`update public.sa_counters set value = greatest(value, ${maxThread}) where name = ${q(counter('thread'))};`);
out.push(`update public.sa_counters set value = greatest(value, ${decisions}) where name = ${q(counter('decision'))};`);
out.push('commit;');
console.log(out.join('\n'));
